### ISSUE TITLE
Unsetting PERSONAL_PAGE_LABELS is not working

### ISSUE THREAD

**Issue by jmlgo** [rotdrop/nextcloud-app-pdf-downloader#1]
When I try to disable this option in my settings I get the toast message `Setting "pageLabels" has been unset successfully.`
After reloading, the option is set again, and generating a file confirms that the option is set.

**Comment by rotdrop** [comment]
Should be fixed by 532ca7a9c077fe0cc3bbcf37fd088ae91eb3f8e9

**Comment by jmlgo** [comment]
Working now! Thanks.
