### ISSUE TITLE
Do we need to install dependencies?

### ISSUE THREAD

**Issue by meichthys** [rotdrop/nextcloud-app-pdf-downloader#13]
It appears that the expected converters are not installed by default. Do we need to install them, or are they packaged with the app?

I tried `apt-get install unoconv` but it still seems to error out when trying to download the pdfs:

![image](https://user-images.githubusercontent.com/10717998/201507139-dd743ee8-f6c1-4bf9-8056-52a77150c65e.png)

**Comment by meichthys** [comment]
After running `apt-get install pdftk` things seem to work. 
If this is something that is required, perhaps we can put a note in the readme about installing it.

**Comment by rotdrop** [comment]
> After running `apt-get install pdftk` things seem to work. If this is something that is required, perhaps we can put a note in the readme about installing it.

Yes, there should be notes about the requirements. In the admin settings one finds at least an overview over the found converters, but the handling of the required/optional converters should be improved.

I'm thinking about admin notifications with install suggestions. I do not plan to bundle converters as this makes it difficult to benefit from software updates.
