### ISSUE TITLE
l10n: Variables are needed to get translated?

### ISSUE THREAD

**Issue by rakekniven** [rotdrop/nextcloud-app-pdf-downloader#19]
https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Controller/MultiPdfDownloadController.php#L649

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/FileSystemWalker.php#L536

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/FileSystemWalker.php#L536

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/FileSystemWalker.php#L538

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/FileSystemWalker.php#L539

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/FileSystemWalker.php#L540

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L320

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L321

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L322

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L375

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L377

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L378

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L379

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L380

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L381

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L382

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/2ee4a85ec72282dd876d8c1baf26ce9ec70b0173/lib/Service/PdfCombiner.php#L383

Please clarify.

Has been reported at Transifex.

**Comment by rotdrop** [comment]
Well, yes, I'd like to have these variables translated. These substitutions occur in filename  and page label templates which are configurable in the personal settings page. Every modern office spreadsheet app does the same thing with the keywords used for defining cell formulas. So it is at least not absurd to have translated keywords.

The substitution back-end understand translated keywords as well as untranslated keywords such that users can choose whether the want to use (example for German) `EXTENSION` or `ERWEITERUNG` etc.

I agree that translatable keywords are questionable, but for this purpose they might make sense. I suppose I should add some `// TRANSLATORS` comments to the source code to clarify the meaning of these variables.

Thank you for submitting this issue. Does my response answer you question?

**Comment by rotdrop** [comment]
> > I agree that translatable keywords are questionable, but for this purpose they might make sense. I suppose I should add some `// TRANSLATORS` comments to the source code to clarify the meaning of these variables.
> 
> Yes, that would be very good. And please add also information if you expect to have such translated variables in UPPERCASE (otherwise you will get a beautiful mix of all variations).

That's a very good point.
