### ISSUE TITLE
Warning when Pdftk is missing instead of error 500

### ISSUE THREAD

**Issue by TtuxX** [rotdrop/nextcloud-app-pdf-downloader#21]
Hi there and Happy New Year!! :)

I activated your app on Truenas Core and got an error 500 on Files app right away.

I have not seen the Install part in the Readme regarding Pdftk. 

Would it be possible to show a message when Pdftk is not detected and to add Install info ? As otherwise users might get Error 500 as I experienced :(

Thank you very much.

Kind regards

**Comment by rotdrop** [comment]
Hi there, I have just renamed my pdftk such that it can no longer be found. I experience also the 500 message, but it actually also states that pdftk cannot be found.

- I suppose the error message should be less verbose and state the reason "pdftk not found" first place at the top
- there is also an error toast and that one really only notifies about the 500 error, that one should really be changed
- when doing background job conversion the error message is just "pdftk could not be found". So this should be ok.

**Comment by rotdrop** [comment]
There is some ongoing work on the branch

https://github.com/rotdrop/nextcloud-app-pdf-downloader/tree/bugfix/check-for-requirements

**Comment by rotdrop** [comment]
Should be solved by #25:

- user gets notified by an appropriate error message
- the admins get notified in a post-install script about missing external programs

So I am closing this issue now.
