### ISSUE TITLE
l10n: Context needed

### ISSUE THREAD

**Issue by rakekniven** [rotdrop/nextcloud-app-pdf-downloader#26]
Please add comments for the translators. See https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#provide-context-hints-for-translators

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/d9a9f37e89139cd02cec812cebfc0faaa58eceb3/lib/Service/AnyToPdf.php#L243

---

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/90aac87e2a908cfd22feaf93e48a350d83deb58a/lib/Service/FileSystemWalker.php#L424
What nodes are these ? Inodes ?

**Comment by rotdrop** [comment]
Thanks for reporting, is this enough?

5f0fa7ee381018b057eae9ae3cb4cba3973ac588

**Comment by rotdrop** [comment]
> Looks good. Not sure if multiple comment lines are supported. Please wait until tomorrow before closing. I will check back.

Yes, they are. I have already tested that here

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/5f0fa7ee381018b057eae9ae3cb4cba3973ac588/src/toolkit/util/pangram.js#L22-L25

Nevertheless the issue can remain open until the comments have been uploaded to Transifex.

**Comment by rotdrop** [comment]
> What nodes are these ? Inodes ?

Nope, just files or directories in the naming chosen by the Nextcloud software developers. I agree that this is too technical.

**Comment by rotdrop** [comment]
> > Yes, they are. I have already tested that here
> 
> Every morning at 5AM IIRC some tools are running on nextcloud server and do the magic of extracting strings and comments and sync them with Transifex. And TX needs to display it correctly. The result I will check and report back.

Yes, but the portion I mentioned in my link above already has been uploaded weeks ago and the comments just looks okay in Transifex:

https://www.transifex.com/nextcloud/nextcloud/translate/#de/pdf_downloader/442493555?q=text%3Abrown
