### ISSUE TITLE
Clues for translators

### ISSUE THREAD

**Issue by silopolis** [rotdrop/nextcloud-app-pdf-downloader#27]
Hi,

First, thanks for sharing your work and extending Nextcloud :)

Could you please add short cues for translators about the meaning of the placeholders in https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/main/lib/Service/PdfCombiner.php#L351, specially DIR_PAGE_NUMBER and DIR_TOTAL_PAGES?

Existing comments do help for the form, not that much for the meaning, e.g. for DIR_PAGE_NUMBER, is that the "page number of the directory", or "number of pages in the directory" which in turn would raise: what's a page in a directory? A file? A page in the sum of pages of all the files in the directory?

Thanks in advance for your support
Have a nice week
J

**Comment by rotdrop** [comment]
I'll have a look and extend the explanations. Thanks for reporting!

**Comment by silopolis** [comment]
Le lun. 16 janv. 2023 à 21:09, Claus-Justus Heine ***@***.***>
a écrit :

> I have added some comments in commit 9357735
> <https://github.com/rotdrop/nextcloud-app-pdf-downloader/commit/93577357e8b906a3acf8d19a7bb91f9a1207a993>
> and 0991247
> <https://github.com/rotdrop/nextcloud-app-pdf-downloader/commit/09912475ac699b711c9c4544cd57774477d1b442>
>
> I hope it is clearer now, otherwise feel free to request better
> explanations ;)
>

Perfect 👌
Thanks 🙏
