### ISSUE TITLE
'Single plain file conversion' could be more explicit

### ISSUE THREAD

**Issue by silopolis** [rotdrop/nextcloud-app-pdf-downloader#32]
Hi,

Translating this left me doubtful of what this really does and, consequently, of the accuracy of my translation!

1. Does single mean individual/one by one/in isolation? Is it defined in opposition to concatenating conversion of multiple files?
2. What is a 'plain file', really? A raw text file?

Thanks in advance for your insights

https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/94f03f7b70938e15806d87c330866664c794ed34/src/PersonalSettings.vue#L326-L349

**Comment by rotdrop** [comment]
Hi there, for the heading I have added a comment, but only just now shortly before you created this issue:
```
TRANSLATORS: This is the heading for a configuration option which enables PDF-conversion of single plain files in addition to converting entire directory trees.
```
The comment will not show up before tomorrow at TX, of course. However, the wording may be incorrect. What I meant is that this option enables the possibility to convert "plain" files in addition being able to converting entire directory trees or archive files.

A better wording has now to wait until the evening in the timezone MET.

**Comment by rotdrop** [comment]
BTW, as I am coming more from a Unix environment, in my head a "plain file" is opposed to directories, symbolic links sockets, pipes, i.e. just a file. I totally agree of course that people are not able to look into my head. I actually expected such an issue to pop up after realizing in the morning that this phrase cannot be translated without further context.

**Comment by rotdrop** [comment]
> Thank you for that perfect translator comment! Life would be so sweet if there was more like this all around…
> 
> > BTW, as I am coming more from a Unix environment, in my head a "plain file" is opposed to directories, symbolic links sockets, pipes, i.e. just a file
> 
> OK, makes perfect sense for us, but I'm afraid it doesn't for the average Nextcloud user… After thinking a bit about it, this looks much better than it used to, and maybe just adding '(no archives, nor special files)' at the end of the hint would be enough to clear all doubts. Let me push this with another typo fix I have hanging…

Your changes are of course very welcome! I Think it would make sense to paraphrase this "thing" as "individual file" in contrast to a collection of files in folders and archive files. I'll have a look at it later.

**Comment by rotdrop** [comment]
I would propose to change this later on to

> Enable conversion of individual files (no archives, nor folders)

Sorry for throwing in pipes and the like; inside Nextcloud we have of course only folders and  "ordinary" files.

Likewise for the heading

> Individual File Conversion
> TRANSLATORS: This is the heading for a configuration option which enables PDF-conversion of individual files in addition to converting entire directory trees or archive files.

**Comment by rotdrop** [comment]
Closing this as completed. Thanks for your bug report!
