### ISSUE TITLE
Compatibility to NC 26

### ISSUE THREAD

**Issue by raffaelone** [rotdrop/nextcloud-app-pdf-downloader#38]
Is there any news about the release of a stable version compatible with Nextcloud 26?

Thanks

**Comment by rotdrop** [comment]
Currently on holiday, the master branch should  work, but a release will not happen before start of August.

22.07.2023 11:54:30 raffaelone ***@***.***>:

**Comment by rotdrop** [comment]
There is  now a new pre-release, I have used NC v27 to generate it. There are now also stableXY branches which contain compiled assets and the vendor subdirectory for v25 - v27.

Can you please test the release? Thanks!

**Comment by raffaelone** [comment]
I've tested v1.1.3-rc1 on NC 25. I take this error from logs but the app works perfectly.

```
[index] Errore: Exception: Class "wapmorgan\UnifiedArchive\Abilities" not found in file '/var/www/nextcloud/apps/pdf_downloader/vendor/wapmorgan/unified-archive/src/Drivers/Zip.php' line 56 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1053
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

```

**Comment by rotdrop** [comment]
> Strange. I'll have a look. Is files_archive also installed? Thinking about incompatible UnifiedArchive versions ...

Seems that I missed some changes in the archive-file library (wapmorgan/...). Still not sure why Abilities is not found. We will see. On-the-fly decryption of archives is probably broken ATM.

**Comment by rotdrop** [comment]
... there will be a next pre-release this evening ;)

**Comment by rotdrop** [comment]
The current prerelease seems to work for NC 25 - 26. I would just label the current state as v1.1.3 and release it.

**Comment by rotdrop** [comment]
I have just uploaded a new release and therefore closing this issue now. In case of problems please feel free to reopen the issue (or add a new one). Thank you for using my app and for the feedback!
