### ISSUE TITLE
Translation sync fails

### ISSUE THREAD

**Issue by nickvergessen** [rotdrop/nextcloud-app-pdf-downloader#39]
Hi there @rotdrop 

Since 2-3 days the translation sync doesn't work anymore for this app as well as https://github.com/rotdrop/nextcloud-app-files-archive

The problem is that this folder exists in the repo: https://github.com/rotdrop/nextcloud-app-pdf-downloader/tree/main/translationfiles
Therefore after syncing master, the bot can not change to another branch anymore:
```
error: The following untracked working tree files would be overwritten by checkout:
	translationfiles/templates/pdf_downloader.pot
Please move or remove them before you switch branches.
Aborting
```

Should we remove the transifex bot or can you remove the directories again?

**Comment by rotdrop** [comment]
Mmmh. I did not change anything, so the problem are your changes from:
```
commit 2426d57fbc557a8819c4969519304392078c2ae0
Author: Nextcloud bot <bot@nextcloud.com>
Date:   Wed Aug 2 02:50:17 2023 +0000

    Fix(l10n): Update Transifex configuration
    
    Signed-off-by: Nextcloud bot <bot@nextcloud.com>
```

which removed the translation template from the git repo. Anyhow, if this is really required I can remove the remaining files from that subdirectory.

**Comment by rotdrop** [comment]
I have removed the subdirectory `translationfiles/` from my git-repo. However, I have no control over the the working-tree generated by the your translation bot. I leave this issue open until the next sync, however, I did now everything that could be done on my side, see e49ec3a af8cb0c 3becd32 16fae84.

**Comment by nickvergessen** [comment]
https://github.com/rotdrop/nextcloud-app-files-archive/tree/stable27/translationfiles/templates

on the stable branches the folder is still present with the problematic file.
But we seem to be on the right track.

Can you try deleting it too, then I give it yet another sync try

**Comment by rotdrop** [comment]
> https://github.com/rotdrop/nextcloud-app-files-archive/tree/stable27/translationfiles/templates
> 
> on the stable branches the folder is still present with the problematic file. But we seem to be on the right track.
> 
> Can you try deleting it too, then I give it yet another sync try

Done.

**Comment by nickvergessen** [comment]
on stable25 it still exists on files archive:
https://github.com/rotdrop/nextcloud-app-files-archive/tree/stable25/translationfiles/templates

**Comment by rotdrop** [comment]
Oops. Too many branches ... sorry for that. I _think_ that there are now no more left-over translationsfiles/ directories ...

**Comment by nickvergessen** [comment]
No error emails on the weekend, so I guess it's solved
