### ISSUE TITLE
i18n: Need context

### ISSUE THREAD

**Issue by rakekniven** [rotdrop/nextcloud-app-pdf-downloader#41]
https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/412d3cf4b3a675d7605ff4688fc8858f874d4b99/src/PersonalSettings.vue#L270

The second sentence is hard to understand. I personally do not understand it.
Please clarify.

Reported at Transifex.

**Comment by rotdrop** [comment]
Thank you for reporting; I'll have a look and  either rephrase the sentence or add suitable hints for the translators.

**Comment by rotdrop** [comment]
Quite late, however, changed to
```
Optionally choose a default destination folder in the
cloud. If left blank PDFs will be generated in the current directory.
```
