### ISSUE TITLE
NC 28 error log

### ISSUE THREAD

**Issue by raffaelone** [rotdrop/nextcloud-app-pdf-downloader#46]
After upgrading from NC 27 to NC 28 the log returns continuously this error:

`[pdf_downloader] Error: /var/www/nextcloud/apps/pdf_downloader/lib/Listener/FilesActionListener.php:220: OCA\PdfDownloader\Listener\FilesActionListener::handle: Unable to add style asset files-sidebar-hooks`

Is there a way to remove it?

Thanks

**Comment by rotdrop** [comment]
It is already fixed in commit a22c8191

**Comment by rotdrop** [comment]
Added a new release, closing this issue.
