### ISSUE TITLE
Icon in settings not visible in dark mode

### ISSUE THREAD

**Issue by meichthys** [rotdrop/nextcloud-app-pdf-downloader#8]
This may not be an issue in older versions of NC, but in NC25RC1 the icon is not visible when using Nextcloud in dark mode:
![image](https://user-images.githubusercontent.com/10717998/192371852-354c7a0f-5f79-4371-b983-5adc7e9afde9.png)

**Comment by meichthys** [comment]
We could probably also capitalize "PDF" and drop the "Personal Settings" from the title since that should be implicit since it is under the Personal settings menu.

**Comment by rotdrop** [comment]
Seems that some art-work has to be done to design something with improved visibility. Thanks for reporting!

**Comment by rotdrop** [comment]
> We could probably also capitalize `PDF` and drop the `, Personal Settings` from the title since that should be implicit since it is under the Personal settings menu.

Please feel free to submit a pull request. Otherwise it will be fixed eventually, but PRs are definitely welcome ;)

**Comment by rotdrop** [comment]
Should be fixed by 9d2114e61b6a136242fd637cf4d6beec79ee63fd ...

**Comment by rotdrop** [comment]
> Should be fixed by [9d2114e](https://github.com/rotdrop/nextcloud-app-pdf-downloader/commit/9d2114e61b6a136242fd637cf4d6beec79ee63fd) ...

@meichthys I have just uploaded a new release candidate. Perhaps you have a chance to test it ... thanks!
